env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
#   - secure: "gJH5oKBV9xacK0ti7/XLSWa48HyyeMYKcMH80bNUV+KCHPzsgUAVrW0sWA+SEA4RNEMgGlZDGfWaEuekGu1OhEp5WM0ZNRTmAuagDizJc9olgFAbx186luJrbDrWis7vJEvmw4w/MaXPSN2jhq/UlPC6mXL5vjZ2L/uiRfJS81DoACSLbrYpbjmfUTuosQYrMMewFwktop5nmQ4HXMbfcokpxjKxbr0K5GsnYkbccxOYaA65ERb3ttrgCLXiK4T49mhWwXiB7BgiRYmt3v1iDULpdGxQlKigr9+5QNoFzvkMM7pzXnufIi5cwMS1xz6EuPpUvnbo6RYXC/cJTLqV+sMga7NF8MbuILIEA89CJOPcsWbARFDUYp7f3pRi0Prn11gzwqheCie2s0m4UN6ODVOAvkNQaxiS0yc+bg0GXrSaPBy4gk306oYpvEYfaJNL6NquCHCD+Xwc5SJobHnUvnQjN4jl1t1DVDZCeHtFV1WTsUjJZQl0e6VAGFKHYiHYcBNURtGECJyodkmGm0vavni/ezkzF7h4sVw4zQuVdnhbfrB3jwv6toZu5+I0i6/PZOOgkLVtrGwDKLSlKibbYOD4bBVk10nZK1St9emGDR1anx+PY/1RhcRazASXqS6qqXEG9UgWiNzEthXU00nUFybU9W48krZxiW35ZiwmX6Q="
#   - secure: "jOK0QJ2tA5FguCn1k1c7EyelJikZm9oD8Zf2wdhyNWl3sLBomBRqadRkZ58jMhoY3WWuwNDYOOrxQTYrS6dySqbmCTpP6oARr76STMBxLhnboSEyntyVjPBT7FTDCgwVIMWv7KdvQNyBi4TT864rCiMPREcCj0CqMwGevlXbVN98hmRYNj5OqFEItn6DD71AUGqgjdaCdsIEQvbbfY4DNWaI4XILh5xDrHNb2y87FqDHXVrmd4qcQAdbMWpXyoCnmnbAxzWE9Nz0/xRkwrCi3QWoAm5YoQS4oVHV2MMpHRu8Lz6C198fgc1cvIq8seeCMG/8pbZMCf6D/9lOWP8Dg5ZJTdVFMbPd2ba1P4l+xw/4Ryy9LOf+pagIShz4NGQw3OkBUaXrdb46963iKxI+XMCLgSi0+SCWMhAXSoH4znonZd1YuqjBnoHKEIKA4pUrARVC/LCVo5vmuKEc6lq7zmTJN0cCKGXrFiTsqro0xo0PTmLI4hvsWmIYvKzwxIKoZNmuGrMsGLhv/+qlYAz//sPDJqdKKX3PZcjFm2lbuSOT4EzmLCFK3diuMHKXe3rtLXEHLCWsaoizi3138hTEL9R/dJ5bcnepoZnbBjzdYBBZQ9IRtJssNaJlqhddL42HraRAkViRBqx2tZndpAi3WjjFd2jsiZf1y2PPi0AdRmk="


addons:
  coverity_scan:
    project:
      name: "evelikov/waffle"
      description: "Build submitted via Travis CI"
    notification_email: emil.l.velikov@gmail.com
    build_command_prepend: "rm -rf build && cmake -H. -Bbuild $CMAKE_OPTIONS"
    build_command:   "cmake --build build --use-stderr -- -k"
    branch_pattern: coverity_scan


branches:
    only:
      - wip/ci
# XXX: tweak this later


language: c
# Android: C++
# OSx: XXX ?


matrix:
  include:
  - os: linux
    compiler: gcc
    env:
    - CMAKE_OPTIONS="-DCMAKE_BUILD_TYPE=Release -Dwaffle_build_manpages=1 -Dwaffle_build_htmldocs=1"
  - os: linux
    compiler: clang
    env:
    - CMAKE_OPTIONS="-DCMAKE_BUILD_TYPE=Release"
# gcc (Android) 32/64bit
# clang (OSx)
# mingw32/64 cross-compile on linux (Win) - 32/64 bit
# mingw32/64 (Win) - 32/64 bit


install:
- sudo add-apt-repository -y ppa:kalakris/cmake
# yay ancient mesa :)
- sudo add-apt-repository -y ppa:xorg-edgers/ppa
# simplify the dependency tracking :)
- sudo add-apt-repository -y ppa:xorg-edgers/piglit
- sudo apt-get update -qq
- sudo apt-get install -qq -y cmake
- sudo apt-get build-dep -qq -y waffle


script:
  - export DISPLAY=:99.0
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x24 &
  - nohup weston &
  - cmake -H. -Bbuild $CMAKE_OPTIONS
  - cmake --build build --use-stderr -- -k
  - cmake --build build --use-stderr --target check -- -k
  - cmake --build build --use-stderr --target check-func -- -k
  - cmake --build build --use-stderr --target package -- -k
  - build/bin/wflinfo -p glx -a gl || echo Failed
  - build/bin/wflinfo -p glx -a gles1 || echo Failed
  - build/bin/wflinfo -p glx -a gles2 || echo Failed
  - build/bin/wflinfo -p glx -a gles3 || echo Failed
  - build/bin/wflinfo -p x11_egl -a gl || echo Failed
  - build/bin/wflinfo -p x11_egl -a gles1 || echo Failed
  - build/bin/wflinfo -p x11_egl -a gles2 || echo Failed
  - build/bin/wflinfo -p x11_egl -a gles3 || echo Failed
  - build/bin/wflinfo -p gbm -a gl || echo Failed
  - build/bin/wflinfo -p gbm -a gles1 || echo Failed
  - build/bin/wflinfo -p gbm -a gles2 || echo Failed
  - build/bin/wflinfo -p gbm -a gles3 || echo Failed
