branches:
    only:
      - wip/ci
# XXX: tweak this later


language: c
# Android: C++
# OSx: XXX ?


env:
  global:
  - MAKEFLAGS=-j2


matrix:
  include:
  - compiler: gcc
    env:
    - APT_PACKAGES="coreutils weston libegl1-mesa-dev libgl1-mesa-dev libgbm-dev libwayland-dev libx11-dev docbook-xsl xsltproc"
    - CMAKE_OPTIONS="-DCMAKE_BUILD_TYPE=Release -Dwaffle_build_manpages=1 -Dwaffle_build_htmldocs=1"
  - compiler: clang
    env:
    - APT_PACKAGES="coreutils weston libegl1-mesa-dev libgl1-mesa-dev libgbm-dev libwayland-dev libx11-dev"
    - CMAKE_OPTIONS="-DCMAKE_BUILD_TYPE=Release"
# gcc (Android) 32/64bit
# clang (OSx)
# mingw32/64 cross-compile on linux (Win) - 32/64 bit
# mingw32/64 (Win) - 32/64 bit


install:
- sudo add-apt-repository -y ppa:kalakris/cmake
- sudo apt-get update -qq
- sudo apt-get install -qq -y cmake
- if [ "$APT_PACKAGES" ]; then sudo apt-get install -qq -y $APT_PACKAGES; fi


script:
  - export DISPLAY=:99.0
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x24 &
  - nohup weston &
  - cmake -H. -Bbuild $CMAKE_OPTIONS
  - cmake --build build --use-stderr -- -k
  - cmake --build build --use-stderr --target check -- -k
  - cmake --build build --use-stderr --target check-func -- -k
  - cmake --build build --use-stderr --target package -- -k

os:
  - linux
#  - osx
# XXX: Android, Windows (cross-compile/native mingw64, msvc)